scripts: clean ipkg-build
Signed-off-by: Huangbin Zhan <zhanhb88@gmail.com>

diff --git a/scripts/ipkg-build b/scripts/ipkg-build
--- a/scripts/ipkg-build
+++ b/scripts/ipkg-build
@@ -7,6 +7,7 @@
 #   Updated to work on Familiar Pre0.7rc1, with busybox tar.
 #   Note it Requires: binutils-ar (since the busybox ar can't create)
 #   For UID debugging it needs a better "find".
+# shellcheck disable=SC3043
 set -e
 
 version=1.0
@@ -16,21 +17,15 @@ TAR="${TAR:-$(command -v tar)}"
 
 # try to use fixed source epoch
 if [ -n "$PKG_SOURCE_DATE_EPOCH" ]; then
-	TIMESTAMP=$(date --date="@$PKG_SOURCE_DATE_EPOCH")
+	TIMESTAMP="$(date --date="@$PKG_SOURCE_DATE_EPOCH")"
 elif [ -n "$SOURCE_DATE_EPOCH" ]; then
-	TIMESTAMP=$(date --date="@$SOURCE_DATE_EPOCH")
+	TIMESTAMP="$(date --date="@$SOURCE_DATE_EPOCH")"
 else
-	TIMESTAMP=$(date)
+	TIMESTAMP="$(date)"
 fi
 
-ipkg_extract_value() {
-	sed -e "s/^[^:]*:[[:space:]]*//"
-}
-
 required_field() {
-	field=$1
-
-	grep "^$field:" < "$CONTROL/control" | ipkg_extract_value
+	grep "^$1:" CONTROL/control | sed -e 's/^[^:]*:[[:space:]]*//'
 }
 
 pkg_appears_sane() {
@@ -44,23 +39,23 @@ pkg_appears_sane() {
 	version="$(required_field Version | sed 's/Version://; s/^.://g;')"
 	arch="$(required_field Architecture)"
 
-	if echo "$pkg" | grep '[^a-zA-Z0-9_.+-]'; then
+	if expr "$pkg" : '[a-zA-Z0-9_\.\+-]\{1,\}' = 0 >/dev/null; then
 		echo "*** Error: Package name $pkg contains illegal characters, (other than [a-z0-9.+-])" >&2
-		PKG_ERROR=1;
+		PKG_ERROR=1
 	fi
 
-	if [ -f "$CONTROL/conffiles" ]; then
-		rm -f "$CONTROL/conffiles.resolved"
+	if [ -f CONTROL/conffiles ]; then
+		rm -f CONTROL/conffiles.resolved
 
-		for cf in $($FIND $(sed -e "s!^/!$pkg_dir/!" "$CONTROL/conffiles") -type f); do
-			echo "${cf#$pkg_dir}" >> "$CONTROL/conffiles.resolved"
+		$FIND $(sed -e "s!^/!$pkg_dir/!" CONTROL/conffiles) -type f | while read -r cf; do
+			echo "${cf#$pkg_dir}" >>CONTROL/conffiles.resolved
 		done
 
-		rm "$CONTROL"/conffiles
-		if [ -f "$CONTROL"/conffiles.resolved ]; then
-			LC_ALL=C sort -o "$CONTROL"/conffiles "$CONTROL"/conffiles.resolved
-			rm "$CONTROL"/conffiles.resolved
-			chmod 0644 "$CONTROL"/conffiles
+		rm CONTROL/conffiles
+		if [ -f CONTROL/conffiles.resolved ]; then
+			LC_ALL=C sort -o CONTROL/conffiles CONTROL/conffiles.resolved
+			rm CONTROL/conffiles.resolved
+			chmod 0644 CONTROL/conffiles
 		fi
 	fi
 
@@ -72,14 +67,14 @@ resolve_file_mode_id() {
 	local var=$1 type=$2 name=$3 id
 
 	case "$name" in
-		root)
-			id=0
+	root)
+		id=0
 		;;
-		*[!0-9]*)
-			id=$(sed -ne "s#^$type $name \\([0-9]\\+\\)\\b.*\$#\\1#p" "$TOPDIR/tmp/.packageusergroup" 2>/dev/null)
+	*[!0-9]*)
+		id=$(sed -ne "s#^$type $name \\([0-9]\\+\\)\\b.*\$#\\1#p" "$TOPDIR/tmp/.packageusergroup" 2>/dev/null)
 		;;
-		*)
-			id=$name
+	*)
+		id=$name
 		;;
 	esac
 
@@ -94,16 +89,16 @@ resolve_file_mode_id() {
 file_modes=""
 usage="Usage: $0 [-v] [-h] [-m] <pkg_directory> [<destination_directory>]"
 while getopts "hvm:" opt; do
-    case $opt in
-	v ) echo "$version"
-	    exit 0
-	    ;;
-	h ) 	echo "$usage"  >&2 ;;
-	m )	file_modes=$OPTARG ;;
-	\? ) 	echo "$usage"  >&2
+	case $opt in
+	v)
+		echo "$version"
+		exit 0
+		;;
+	h) echo "$usage" >&2 ;;
+	m) file_modes=$OPTARG ;;
+	\?) echo "$usage" >&2 ;;
 	esac
 done
-
 
 shift $((OPTIND - 1))
 
@@ -115,8 +110,8 @@ case $# in
 	;;
 2)
 	dest_dir=$2
-	if [ "$dest_dir" = "." ] || [ "$dest_dir" = "./" ] ; then
-	    dest_dir=$PWD
+	if [ "$dest_dir" = . ] || [ "$dest_dir" = ./ ]; then
+		dest_dir=$PWD
 	fi
 	;;
 *)
@@ -125,76 +120,77 @@ case $# in
 	;;
 esac
 
-pkg_dir="$(realpath "$1")"
-
-if [ ! -d "$pkg_dir" ]; then
-	echo "*** Error: Directory $pkg_dir does not exist" >&2
+pkg_dir="$(cd "$1" 2>/dev/null && pwd -P)" || {
+	echo "*** Error: Directory $1 does not exist" >&2
 	exit 1
-fi
+}
 
 # CONTROL is second so that it takes precedence
-CONTROL=
-[ -d "$pkg_dir"/CONTROL ] && CONTROL=CONTROL
-if [ -z "$CONTROL" ]; then
+[ -d "$pkg_dir/CONTROL" ] || {
 	echo "*** Error: Directory $pkg_dir has no CONTROL subdirectory." >&2
 	exit 1
-fi
+}
 
-if ! pkg_appears_sane "$pkg_dir"; then
+pkg_appears_sane "$pkg_dir" || {
 	echo >&2
 	echo "ipkg-build: Please fix the above errors and try again." >&2
 	exit 1
-fi
+}
 
 tmp_dir=$dest_dir/IPKG_BUILD.$$
 mkdir "$tmp_dir"
 
-echo $CONTROL > "$tmp_dir"/tarX
+echo CONTROL >"$tmp_dir/tarX"
 cd "$pkg_dir"
 for file_mode in $file_modes; do
 	case $file_mode in
-	/*:*:*:*)
-	    ;;
+	/*:*:*:*) ;;
+
 	*)
-	    echo "ERROR: file modes must use absolute path and contain user:group:mode"
-	    echo "$file_mode"
-	    exit 1
-	    ;;
+		echo "ERROR: file modes must use absolute path and contain user:group:mode"
+		echo "$file_mode"
+		exit 1
+		;;
 	esac
 
-	mode=${file_mode##*:}; path=${file_mode%:*}
-	group=${path##*:};     path=${path%:*}
-	user=${path##*:};      path=${path%:*}
+	mode=${file_mode##*:}
+	path=${file_mode%:*}
+	group=${path##*:}
+	path=${path%:*}
+	user=${path##*:}
+	path=${path%:*}
 
-	if ! resolve_file_mode_id uid user "$user"; then
+	uid=
+	gid=
+	resolve_file_mode_id uid user "$user" || {
 		echo "ERROR: unable to resolve uid of $user" >&2
 		exit 1
-	fi
+	}
 
-	if ! resolve_file_mode_id gid group "$group"; then
+	resolve_file_mode_id gid group "$group" || {
 		echo "ERROR: unable to resolve gid of $group" >&2
 		exit 1
-	fi
+	}
 
 	chown "$uid:$gid" "$pkg_dir/$path"
-	chmod  "$mode" "$pkg_dir/$path"
+	chmod "$mode" "$pkg_dir/$path"
 done
-$TAR -X "$tmp_dir"/tarX --format=gnu --numeric-owner --sort=name -cpf - --mtime="$TIMESTAMP" . | gzip -n - > "$tmp_dir"/data.tar.gz
+$TAR -X "$tmp_dir/tarX" --format=gnu --numeric-owner --sort=name -cpf - --mtime="$TIMESTAMP" . | gzip -n - >"$tmp_dir/data.tar.gz"
 
 installed_size=$(stat -c "%s" "$tmp_dir"/data.tar.gz)
 sed -i -e "s/^Installed-Size: .*/Installed-Size: $installed_size/" \
-	"$pkg_dir"/$CONTROL/control
+	"$pkg_dir/CONTROL/control"
 
-( cd "$pkg_dir"/$CONTROL && $TAR --format=gnu --numeric-owner --sort=name -cf -  --mtime="$TIMESTAMP" . | gzip -n - > "$tmp_dir"/control.tar.gz )
-rm "$tmp_dir"/tarX
+(cd "$pkg_dir/CONTROL" && $TAR --format=gnu --numeric-owner --sort=name -cf - --mtime="$TIMESTAMP" . | gzip -n - >"$tmp_dir/control.tar.gz")
+rm "$tmp_dir/tarX"
 
-echo "2.0" > "$tmp_dir"/debian-binary
+echo 2.0 >"$tmp_dir/debian-binary"
 
 pkg_file=$dest_dir/${pkg}_${version}_${arch}.ipk
 rm -f "$pkg_file"
-( cd "$tmp_dir" && $TAR --format=gnu --numeric-owner --sort=name -cf -  --mtime="$TIMESTAMP" ./debian-binary ./data.tar.gz ./control.tar.gz | gzip -n - > "$pkg_file" )
+(cd "$tmp_dir" && $TAR --format=gnu --numeric-owner --sort=name -cf - --mtime="$TIMESTAMP" ./debian-binary ./data.tar.gz ./control.tar.gz | gzip -n - >"$pkg_file")
 
-rm "$tmp_dir"/debian-binary "$tmp_dir"/data.tar.gz "$tmp_dir"/control.tar.gz
+rm "$tmp_dir/debian-binary" "$tmp_dir/data.tar.gz" "$tmp_dir/control.tar.gz"
 rmdir "$tmp_dir"
 
 echo "Packaged contents of $pkg_dir into $pkg_file"
